config/routes.rb
Rails.application.routes.draw do
  resources :movies
  resources :clients
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "clients#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/client.rb
class Client < ApplicationRecord
    has_many :movies
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :client, optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %i[ show edit update destroy ]
  before_action :consulta_peliculas

  # GET /clients or /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1 or /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients or /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to client_url(@client), notice: "Client was successfully created." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to client_url(@client), notice: "Client was successfully updated." }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.movies.update_all(client_id: nil)
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url, notice: "Client was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:name, :age)
    end

    def consulta_peliculas
      @movies = Movie.all
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: %i[ show edit update destroy ]
  before_action :consulta_clientes, only: %i[show edit new]

  # GET /movies or /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1 or /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies or /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully created." }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1 or /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully updated." }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1 or /movies/1.json
  def destroy
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to movies_url, notice: "Movie was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def movie_params
      params.require(:movie).permit(:name, :client_id)
    end

    def consulta_clientes
        @clients = Client.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/clients/_client.html.erb
<div id="<%= dom_id client %>">
    <th scope="row"><%= client.id %></th>
    <td><%= client.name %></td>
    <td><%= client.age %></td>
</div>

app/views/clients/_form.html.erb
<%= form_with(model: client) do |form| %>
  <% if client.errors.any? %>
    <div style="color: white">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
        <% client.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="card text-bg-dark mb-3 my-5">
    <div class="card-body">
      <div class="d-flex justify-content-center">
        <div>
          <%= form.label :name, style: "display: block", class:"card-text" %>
          <%= form.text_field :name, class:"form-control" %>
          <%= form.label :age, style: "display: block", class:"card-text" %>
          <%= form.text_field :age, class:"form-control" %>
        <div>
          <%= form.submit class:"btn button3 mt-3 mx-5" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1 class="mt-5">Editing client</h1>

<%= render "form", client: @client %>

<br>

<div class="d-flex justify-content-center">
  <%= link_to "Show this client", @client, class:"mx-3 mb-3 btn button3" %>
  <%= link_to "Back to clients", clients_path, class:"mx-3 mb-3 btn button3" %>
</div>

app/views/clients/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Clients</h1>
<div id="clients">
  <table class="table">
    <thead class="table-dark">
      <tr>
        <th scope="col">id</th>
          <th scope="col">Name</th>
          <th scope="col">Age</th>
          <th scope="col">Movie</th>
          <th scope="col" colspan="1">See More Info</th>
      </tr>
    </thead>
    <tbody id="myTable">
      <% @clients.each do |client| %>
        <tr>
          <%= render client %>
          <% if client.movies.any? %>
            <td><%= client.movies.last.name %></td>
          <% else %>
            <td>has not rented yet</td>
          <% end %>
          <td><%= link_to "Show this Client", client, class:"btn" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <p>
    <%= link_to "New Client", new_client_path, class:"submit button3" %>
  </p>
</div>

app/views/clients/new.html.erb
<h1 class="mt-5">New client</h1>

<%= render "form", client: @client %>

<br>

<div class="d-flex justify-content-center">
  <%= link_to "Back to clients", clients_path, class:"btn button3 mb-3" %>
</div>

app/views/clients/show.html.erb
<p style="color: green"><%= notice %></p>
<h1>Client information</h1>
<table class="table mt-5">
  <thead class="table-dark">
    <tr>
      <th scope="col">id</th>
        <th scope="col">Name</th>
        <th scope="col">Age</th>
    </tr>
  </thead>
  <tbody>
    <%= render @client %>
  </tbody>
</table>
<h2>RENTED MOVIES</h2>
<table class="table mt-5">
  <thead class="table-dark">
    <tr>
      <th scope="col">id</th>
      <th scope="col">Title</th>
    </tr>
  </thead>
  <tbody>
    <% @client.movies.each do |c| %>
      <tr>
        <td><%= c.id %></td>
        <td><%= c.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="my-5">
  <%= link_to "Edit Info", edit_client_path(@client), class:"btn button3" %> |
  <%= link_to "Back to clients", clients_path, class:"btn button3" %>
  <%= button_to "Delete", @client, method: :delete, class:"btn button3 mt-3" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blockbuster</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
      <div class="container">
        <%= link_to "Blockbuster", root_path, class:"navbar-brand" %>
        <div class="collapse navbar-collapse d-flex flex-row-reverse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to "Clients", clients_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Movies", movies_path, class:"nav-link" %>
            </li>
          </ul>
        </div>
      </div>
  </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie) do |form| %>
  <% if movie.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
        <% movie.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="card text-bg-dark mb-3 my-5">
    <div class="card-body">
      <div class="d-flex justify-content-center">
        <div>
          <%= form.label :name, style: "display: block", class:"card-text" %>
          <%= form.text_field :name, class:"form-control" %>
          <%= form.label :client_id, style: "display: block", class:"card-text" %>
          <%= form.collection_select :client_id, @clients, :id, :name, prompt: true, class:"form-select" %>
        <div>
          <%= form.submit class:"btn button3 mt-3 mx-5" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/movies/_movie.html.erb
<div id="<%= dom_id movie %>">
    <th scope="row"><%= movie.id %></th>
    <td><%= movie.name %></td>
    <% if movie.client != nil %>
        <td><%= movie.client.name %></td>
    <% else %>
        <td>has not rented yet</td>
    <% end %>
</div>

app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render "form", movie: @movie %>

<br>

<div class="d-flex justify-content-center">
  <%= link_to "Show this movie", @movie, class:"mx-3 mb-3 btn button3" %>
  <%= link_to "Back to movies", movies_path, class:"mx-3 mb-3 btn button3" %>
</div>

app/views/movies/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Movies</h1>
<div id="movies">
  <table class="table">
    <thead class="table-dark">
      <tr>
        <th scope="col">id</th>
        <th scope="col">Name</th>
        <th scope="col">Client</th>
        <th scope="col">See More Info</th>
      </tr>
    </thead>
    <tbody id="myTable">
      <% @movies.each do |movie| %>
        <tr>
          <%= render movie %>
           <td><%= link_to "Show this Movie", movie, class:"btn" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <p>
    <%= link_to "New Movie", new_movie_path, class:"submit button3" %>
  </p>
</div>

app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render "form", movie: @movie %>

<br>

<div class="d-flex justify-content-center">
  <%= link_to "Back to movies", movies_path, class:"btn button3 mb-3" %>
</div>

app/views/movies/show.html.erb
<p style="color: green"><%= notice %></p>
<table class="table mt-5">
  <thead class="table-dark">
    <tr>
      <th scope="col">id</th>
      <th scope="col">Nombre</th>
      <th scope="col">Cliente</th>
    </tr>
  </thead>
  <tbody>
    <%= render @movie %>
   </tbody>
  </table>
<div class="my-5">
  <%= link_to "Edit this movie", edit_movie_path(@movie), class:"btn button3" %> |
  <%= link_to "Back to movies", movies_path, class:"btn button3" %>

  <%= button_to "Destroy this movie", @movie, method: :delete, class:"btn button3 mt-3" %>
</div>